### PR TITLE
Remove else from CoreListener

### PR DESCRIPTION
**Pull request by szepeviktor**
`else` is no one's friend

### CODE REVIEW

**Comment by Pierre-Lannoy** [comment]
Hello Viktor!
Sorry to ask, I'm not totally aware of these sort of things... Could you tell me why you suggest not to use `else`? Is it in this specific case or is it a general recommandation?

**Comment by szepeviktor** [comment]
`else` adds a branch, it'll be more complex, those pesky indentations!
Some standards ban them: https://github.com/object-calisthenics/phpcs-calisthenics-rules#2-do-not-use-else-keyword

**Comment by szepeviktor** [comment]
Another good one from the same person: https://www.youtube.com/watch?v=crSUWtRYw-M

**Comment by Pierre-Lannoy** [comment]
Aha. You (and Adam Wathan) convinced me :)
I will merge your PR and will try to do this way in the billions of places where I did it badly. As and as I will refactor classes...
Thanks for the hint.

**Pull request merged**
